### ISSUE TITLE
Missing values

### ISSUE THREAD

**Issue by tknijnen** [isb-cgc/ISB-CGC-Webapp#304]
More of an opinion maybe, but I do think that plotting points (in scatter plots for which one of the two data types is missing) on the right and top is weird and visually misleading. Why not simply discard the points that don't have measurements for both data types?

**Comment by smrgit** [comment]
If the user has selected a cohort with, for example, 1000 samples, and they create a gene-expression vs copy-number plot which winds up having only 400 points in it, that we should explain why.  Perhaps we could provide some counts information in a panel or legend indicating how many points are being plotted and why (or why not).  The other reason to actually plot the points along the edges is so that users could see if the distribution of those points along that one dimension looks similar or different from the other points that are being plotted.  

Thoughts?
