### ISSUE TITLE
IGV getting 401

### ISSUE THREAD

**Issue by Gibbsdavidl** [isb-cgc/ISB-CGC-Webapp#839]
Getting 401 errors when trying to use IGV..

**Comment by s-paquette** [comment]
@Gibbsdavidl Have you approved popup windows for the WebApp's site? When using IGV that's how Google authenticates, and a 401 often means the popup can't display so you can't authenticate yourself for access. In Chrome the 'popup blocked' alert appears on the far right of your URL bar.

**Comment by Gibbsdavidl** [comment]
Pretty sure I'm authenticated. Signed in through the NIH page. If I don't sign in with NIH creds, I can't even pick samples to start IGV.

![image](https://user-images.githubusercontent.com/561865/37918892-350a3be8-30d7-11e8-886a-0f2e6e025377.png)

**Comment by Gibbsdavidl** [comment]
![image](https://user-images.githubusercontent.com/561865/37918928-508ecc12-30d7-11e8-853c-ee6569dd8591.png)

**Comment by s-paquette** [comment]
@Gibbsdavidl Although you have to sign in to NIH to pick samples, you also have to reconfirm your Google login when you go to view them in IGV. This is for security reasons, and because your Google ID is the one with the actual sequence file access. However, this quick reaffirmation is done via a popup window instead of a redirect, so if you have popups blocked you won't see it. (And sadly the browser alert is very difficult to see in Chrome.) If you're not being prompted to do that then it will fail to display the sample.

**Comment by Gibbsdavidl** [comment]
OK!  Got it!  Works.

**Comment by s-paquette** [comment]
Excellent!
